version: '3.7'

services:
  web:
    container_name: telegram-web
    tty: true
    build: ./
    restart: always
#    command: python -m bot
    volumes:
      - ./bot:/usr/src/app/bot
    env_file: .env
    depends_on:
      - db
      - cache
  cache:
    container_name: telegram-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    env_file: .env
    command: /bin/sh -c "redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PASSWORD"
    volumes:
      - cache:/data
  db:
    container_name: telegram-db
    image: postgres:14.1-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
#      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
  cache:
    driver: local
